server:
  port: 8081

spring:
  application:
    name: demo
  ai:
    mcp:
      server:
        name: enterprise-order-mcp-system
        version: 1.0.0
        # 指定使用流式HTTP无状态协议
        protocol: STREAMABLE

nacos:
  server-addr: 127.0.0.1:8848
  username: nacos
  password: zhumeng420

agentscope:
  nacos:
    server-addr: 127.0.0.1:8848
    username: nacos
    password: 6vGzZaDdUCU8
  a2a:
    nacos:
      registry:
        enabled: true
        set-as-latest: true
        enabled-register-endpoint: true
